### ISSUE TITLE
README.md wrong parameter description

### ISSUE THREAD

**Issue by jclopes** [ricmoo/scrypt-js#10]
According to the scrypt RFC (https://tools.ietf.org/html/rfc7914#section-2) the 'p' parameter is the parallelization factor and 'r' is the block size.

**Comment by ricmoo** [comment]
You are absolutely correct. I will correct the documentation this evening.

**Comment by ricmoo** [comment]
https://github.com/ricmoo/scrypt-js/commit/cc9fa4c8d096de240367fe5406b3f2775ccdfc35

Thanks again!
