### ISSUE TITLE
[Bug] Error when input password more than 64byte

### ISSUE THREAD

**Issue by ikeji** [ricmoo/scrypt-js#11]
How to reproduce:
1. Open the page: http://ricmoo.github.io/scrypt-js/
2. Input password more than 64 bytes.
3. Click "Compute scrypt"

This make a error:
```
scrypt.js:90 Uncaught TypeError: p.push is not a function
    at SHA256 (scrypt.js:90)
    at PBKDF2_HMAC_SHA256_OneIter (scrypt.js:117)
    at scrypt (scrypt.js:285)
    at HTMLInputElement.submit.onclick ((index):254)
```

```scrypt``` function passes the password to  ```PBKDF2_HMAC_SHA256_OneIter``` function,
When password is more than 64bytes,  ```PBKDF2_HMAC_SHA256_OneIter``` function run ```SHA256``` for password.
```SHA256``` expects that the argument is Array but user uses ```Buffer```.

I think  ```PBKDF2_HMAC_SHA256_OneIter``` should convert password to Array or ```scrypt``` should only support Array.

**Comment by ricmoo** [comment]
Wow. Good catch. I will investigate this more in the morning, but I suspect you are correct. I have moved aes-js and ethers.js to use "arrayish" objects and should do the same for scypt-js.

This is also a test case I will certainly add. I vaguely recall at the time I implemented this thinking I needed to investigate what Colin's algorithm does when the password is longer than the block size.

Thanks!

**Comment by cryptofuture** [comment]
Can approve. And its very serious bug.

**Comment by ricmoo** [comment]
Fixed!

Added test cases generated using the official C implementation.

Thanks! :)
