### ISSUE TITLE
node-scrypt don't support Node v12 

### ISSUE THREAD

**Issue by gingerhot** [ricmoo/scrypt-js#18]
Similar error when installing a package that depends on `scrypt-js` as this issue: https://github.com/barrysteyn/node-scrypt/issues/193

Could you give any help on it? Thanks in advance!

**Comment by ricmoo** [comment]
I don’t think I depend on NaN for anything in this package, is it not working? I haven’t tried node 12 yet, but will check on it this week.

**Comment by gingerhot** [comment]
@ricmoo Thank you for response. And I use [this package](https://github.com/trufflesuite/truffle/tree/develop/packages/truffle-hdwallet-provider) under node v12, and building failed with a similar errors. I'm not sure if it is due to `scrypt-js` but it must be relative to `node-scrypt`.

**Comment by ricmoo** [comment]
I've just confirmed that `script-js` works fine in node v12.

I've never used the `node-scrypt` package, but that is unrelated to this repository and not a project I have anything to do with...

Maybe you can convince your upstream dependencies to switch to scrypt-js, or by the looks of it, switch to my `ethers` library, which uses `scrypt-js`. :)

**Comment by gingerhot** [comment]
@ricmoo I see. And have a glance at `ethers` and it looks nice, I'll have a try. Thank you very much!
