### ISSUE TITLE
README issues or questions

### ISSUE THREAD

**Issue by lll000111** [ricmoo/scrypt-js#22]
# 1. scrypt in node's "crypto"

The README still points to node-scrypt - last updated 4 years ago (related issue: #18).

However, it seems node.js's own crypto module supports scrypt so maybe the link should just say to use that implementation?

https://nodejs.org/api/crypto.html#crypto_crypto_scrypt_password_salt_keylen_options_callback

# ~~2. Code example reference to "buffer.js"~~

**EDIT invalid**, for some reason I overlooked the "thirdparty" folder. Text removed.

# 3. Why Buffer?

Why not just use a TypedArray? I'm missing an explanation for why I'm told to use the node.js Buffer emulation.

That soft dependency seems like significant overhead overhead, it's far more than the scrypt package itself!

# 4. Return type

Document the return type.

On node.js I get a Buffer. Here it seems I get an Array (I only looked [at the source](https://github.com/ricmoo/scrypt-js/blob/master/scrypt.js#L156)? Of what exactly? Without TypeScript-like types it's really hard to see what I get - maybe add a ".d.ts" file with that information as TypeScript types? The example code just uses console.log, which because of implicit JS type conversions toString() does not tell me anything useful. Normally I would expect a Buffer, no?

**Comment by picasticks** [comment]
I'm just a user of this library, but FYI there's no strict dependency on node.js Buffer. You can just use native [TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) to convert to a Uint8Array. Or another library if you prefer.

An example:
```
let password = "foo", salt = "bar";
const scryptPromise = scrypt.scrypt(
  new TextEncoder().encode(password.normalize('NFKC')),
  new TextEncoder().encode(salt.normalize('NFKC')),
  N,
  r,
  p,
  dkLen,
  progressCallback
);
```

**Comment by ricmoo** [comment]
Sorry for the long delay.

I've added TypeScript files and updated the README.

The Buffer dependency is only for the web demo, which could easily be removed in the future; I think I only use it for things which my [strings library](https://www.npmjs.com/package/@ethersproject/strings) could handle, I just haven't had time to do it and it is fairly low priority, I think?

I'm going to close this now, but please feel free to re-open if you feel something wasn't addressed.

Thanks! :)
