### ISSUE TITLE
Demo doesn't accept hex salts longer than 2 nibbles

### ISSUE THREAD

**Issue by joallard** [ricmoo/scrypt-js#25]
On the [demo page](http://ricmoo.github.io/scrypt-js/), entering any reasonable salt and selecting hex will return error: "salt: invalid hex string"

The code:
```js
 } else if (form.indexOf('hex') >= 0) {
                    if (!value.match(/^[0-9A-F][0-9A-F]$/i)) {
                        throw new Error(field + ': invalid hex string');
                    }
                    return new buffer.SlowBuffer(value, 'hex');
                }
```

**Comment by ricmoo** [comment]
That doesn't seem like the right thing to do. :p

I need to spruce up this and a few other packages, which I'll try to get to over the weekend.

**Comment by joallard** [comment]
Fantastic, thanks!

**Comment by ricmoo** [comment]
This should now be fixed. I apparently never updated the gh-pages branch, which is what was serving that demo page. The code was fixed at some point in master.

The gh-pages now points to master, and I've updated the tool to use the latest version of the library, so things should be good now.

Closing, but if there is still a problem, please feel free to re-open.

Thanks! :)

**Comment by joallard** [comment]
Awesome, thanks @ricmoo !
